"""Generate data for wflow from terrain attributes generated before"""

import os
from typing import Tuple

import xarray as xr
import numpy as np
import geopandas as gpd
import pandas as pd
import pyflwdir
from hydromt import flw

from pathlib import Path


class TerrainDataWflow:
    """This class is to generate terrain data for wflow"""

    def __init__(
            self,
            path: Path
    ) -> None:
        """
        Generate terrain data for wflow
        https://deltares.github.io/hydromt_wflow/stable/_examples/prepare_ldd.html

        Parameters
        -----------
        path: Path
            Common path to the directory that contains necessary files to generate terrain data for wflow
        """
        self.path = path

        # The filenames below are expected to be in the path.
        # They will be generated by generate_terrain_attributes.py module
        # They will be changed in the future into argument style of the function.
        # At the moment, the names of these files are kept for easily checking the basic automation
        self.ds_hydro_org = xr.open_dataarray(self.path / "dem_for_wflow_coarser_nodeps_crs.tif")
        self.gdf_riv_org = gpd.read_file(self.path / "streams_d8_area_strahler.shp")

        # Convert uparea column to numeric
        self.gdf_riv_org['uparea'] = pd.to_numeric(
            self.gdf_riv_org['uparea'], errors='coerce'
        )

    def d8_flow_direction_generator(self) -> Tuple[
        pyflwdir.FlwdirRaster,
        xr.Dataset,
        tuple[str, ...]
    ]:
        """
        Generate D8 flow direction

        Returns
        -------
        flwdir : pyflwdir.FlwdirRaster
            Streams' flow direction
        ds_hydro : xr.Dataset
            Array of terrain's information
        dims : tuple[str, ...]
            Dimension of ds_hydro array
        """
        # Derive flow directions with outlets at the edges
        da_flwdir = flw.d8_from_dem(
            da_elv=self.ds_hydro_org.squeeze(),
            max_depth=-1,    # max depression pour point depth; -1 means no local pits
            outlets="edge",  # option: "edge" (default), "min", "idxs_pit"
            idxs_pit=None,
            gdf_riv=self.gdf_riv_org,  # user supplied river network to aid flow direction derivation
            riv_burn_method="uparea",  # options: "fixed" (default), "rivdph", "uparea"
        )

        # Convert to vector
        flwdir = flw.flwdir_from_da(
            da_flwdir,
            ftype='infer',
            check_ftype=True
        )

        # Create a new ds_hydro dataset with the river-burnt flow directions
        ds_hydro = da_flwdir.to_dataset(name='flwdir')
        ds_hydro = ds_hydro.raster.gdal_compliant()

        # Extract dimensions
        dims = ds_hydro.raster.dims

        return flwdir, ds_hydro, dims

    def terrain_and_stream_generator(
            self,
            flwdir: pyflwdir.FlwdirRaster,
            ds_hydro: xr.Dataset,
            dims: tuple[str, ...],
            long_name: str,
            units: str,
            variable_name: str
    ) -> xr.Dataset:
        """
        Generate dataset of terrain and stream dataset

        Parameters
        ----------
        flwdir : pyflwdir.FlwdirRaster
            Streams' flow direction
        ds_hydro : xr.Dataset
            Array of terrain's information
        dims : tuple[str, ...]
            Dimension of ds_hydro array
        long_name : str
            Name of terrain attributes like slope, basin id, etc.
        units : str
            Unit of the terrain attributes
        variable_name : str
            Name of the variable showing the terrain attributes

        Returns
        -------
        ds_hydro : xr.Dataset
            Array of terrain's information in which other data were added
        """
        # Generate terrain dataset
        terrain_data = flwdir.dem_adjust(
            elevtn=self.ds_hydro_org.squeeze().values
        )
        attrs = {
            "_FillValue": -9999,
            "long_name": long_name,
            "units": units
        }

        # Add terrain/stream attribute
        ds_hydro[f'{variable_name}'] = xr.Variable(
            dims,
            terrain_data,
            attrs=attrs
        )

        return ds_hydro

    def slope_generator(
            self,
            ds_hydro: xr.Dataset,
            dims: tuple[str, ...]
    ) -> xr.Dataset:
        """
        Generate terrain attributes - slope

        Parameters
        ----------
        ds_hydro: xr.Dataset
            Array of terrain's information used to add slope
        dims:
            Dimension of ds_hydro

        Returns
        -------
        ds_hydro : xr.Dataset
            Array of terrain's information in which slope data were added
        """
        # Generate slope
        slope = pyflwdir.dem.slope(
            elevtn=ds_hydro['elevtn'].values,
            nodata=ds_hydro['elevtn'].raster.nodata,
            latlon=ds_hydro.raster.crs.is_geographic,  # True if geographic crs, False if projected crs
            transform=ds_hydro['elevtn'].raster.transform
        )

        # Generate attributes for the slope
        attrs = {
            "_FillValue": -9999,
            "long_name": 'lndslp',
            "units": 'm/m'
        }

        # Add to hydro dataset
        ds_hydro['lndslp'] = xr.Variable(
            dims,
            slope,
            attrs=attrs
        )

        return ds_hydro

    def basin_generator(
            self,
            flwdir: pyflwdir.FlwdirRaster,
            ds_hydro: xr.Dataset,
            dims: tuple[str, ...]
    ) -> Tuple[xr.Dataset, gpd.GeoDataFrame]:
        """
        Generate terrain attributes - basin

        Parameters
        ----------
        flwdir: pyflwdir.FlwdirRaster
            Streams' flow direction
        ds_hydro: xr.Dataset
            Array of terrain's information used to add basin
        dims: tuple[str, ...]
            Dimension of ds_hydro

        Returns
        -------
        ds_hydro : xr.Dataset
            Array of terrain's information in which basin data were added
        gdf_basins : gpd.GeoDataFrame
            Basin polygons
        """
        # Generate basin
        basins = flwdir.basins(
            idxs=flwdir.idxs_pit
        ).astype(np.int32)

        # Generate attributes
        attrs = {
            "_FillValue": 0,
            "long_name": 'basin ids',
            "units": '-'
        }

        # Add basins to the hydro dataset
        ds_hydro['basins'] = xr.Variable(
            dims,
            basins,
            attrs=attrs
        )

        # Add basins to geopandas dataframe
        gdf_basins = ds_hydro['basins'].raster.vectorize()

        return ds_hydro, gdf_basins

    def write_out_hydro_dataset(
            self,
            ds_hydro: xr.Dataset,
            gdf_basins: gpd.GeoDataFrame
    ) -> None:
        """
        Generate terrain attributes - basin

        Parameters
        ----------
        ds_hydro: xr.Dataset
            Array of terrain's information
        gdf_basins: gpd.GeoDataFrame
            Basin polygons
        """
        # Write out hydro dataset
        ds_hydro.raster.to_mapstack(
            root=os.path.join(
                self.path,
                'merit_hydro'
            ),
            driver='GTiff'
        )

        # Rename basins column
        gdf_basins = gdf_basins.rename(
            columns={'value': 'basid'}
        )

        # Write out basin dataframe
        gdf_basins.to_file(
            os.path.join(
                self.path,
                'da_hydro_basins.gpkg'
            )
        )

    def terrain_data_for_wflow_generator(self) -> None:
        """Generate terrain data for wflow"""
        # Generate D8 flow direction
        flwdir, ds_hydro, dims = self.d8_flow_direction_generator()

        # Generate elevation data
        ds_elevation = self.terrain_and_stream_generator(
            flwdir,
            ds_hydro,
            dims,
            'corrected elevation',
            'm',
            'elevtn'
        )

        # Generate upstream area using ds_elevation
        # which is just generated
        ds_upstream_area = self.terrain_and_stream_generator(
            flwdir,
            ds_elevation,
            dims,
            'upstream area',
            'km2',
            'uparea'
        )

        # Generate stream strahler order using ds_upstream_area
        # which is just generated
        ds_strord = self.terrain_and_stream_generator(
            flwdir,
            ds_upstream_area,
            dims,
            'stream order',
            '-',
            'strord'
        )

        # Generate slope data
        ds_slope = self.slope_generator(
            ds_strord,
            dims
        )

        # Generate basins
        ds_basins, gdf_basins = self.basin_generator(
            flwdir,
            ds_slope,
            dims
        )

        # Write out hydro dataset
        self.write_out_hydro_dataset(
            ds_basins,
            gdf_basins
        )
